[package]
name = "flightstick-nurbs"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.3"
bsfun = { git = "https://github.com/dorianprill/bsfun.git", version = "0.1.0" }
evdev-rs = "0.6.1"

[profile.release]
lto = true
